Update GitHub Actions workflows
Changed in both workflows:
- Replaced major versions for actions with commit hashes of specific versions to avoid malicious versions.
- Replaced actions/cache and bespoke Composer install with ramsey/composer-install for simplicity.

Changed in Lint workflow:
- Replaced PHP 8.3 with latest version.

Changed in Test workflow:
- Fixed Cronjob schedule; run only once monthly.
- Fixed installation of Composer as dev dependency.
- Updated list of PHP versions to test to include 8.4, 8.5, and 8.6.
- Dropped unsupported Composer versions 2.3–2.8.
- Dropped unused caching of Composer dependencies.

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -5,8 +5,8 @@ name: "Lint"
 #
 # Based on workflows from Composer:
 # 
-# * https://github.com/composer/composer/blob/2.5.4/.github/workflows/lint.yml
-# * https://github.com/composer/composer/blob/2.5.4/.github/workflows/phpstan.yml
+# * https://github.com/composer/composer/blob/2.9.8/.github/workflows/lint.yml
+# * https://github.com/composer/composer/blob/2.9.8/.github/workflows/phpstan.yml
 #
 
 on:
@@ -17,10 +17,6 @@ on:
   pull_request:
     tags-ignore:
       - '**'
-
-env:
-  COMPOSER_FLAGS: "--ansi --no-interaction --prefer-dist"
-  SYMFONY_PHPUNIT_VERSION: ""
 
 permissions:
   contents: read
@@ -33,18 +29,20 @@ jobs:
 
     steps:
       - name: "Checkout"
-        uses: "actions/checkout@v6"
+        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6.0.2
 
       - name: "Setup PHP"
-        uses: "shivammathur/setup-php@v2"
+        uses: "shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc" # 2.37.1
         with:
           coverage: "none"
           extensions: "intl, zip"
-          ini-values: "memory_limit=-1, phar.readonly=0, error_reporting=E_ALL, display_errors=On"
+          ini-values: "memory_limit=-1, error_reporting=E_ALL, display_errors=On"
           php-version: "latest"
 
-      - name: "Install dependencies from composer.lock"
-        run: "composer install ${{ env.COMPOSER_FLAGS }}"
+      - name: "Install Composer dependencies"
+        uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # 4.0.0
+        with:
+          dependency-versions: highest
 
       - name: "Validate composer.json"
         run: "composer validate --strict"
@@ -58,14 +56,14 @@ jobs:
       matrix:
         php-version:
           - "7.2"
-          - "8.3"
+          - "latest"
 
     steps:
       - name: "Checkout"
-        uses: "actions/checkout@v6"
+        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6.0.2
 
       - name: "Setup PHP"
-        uses: "shivammathur/setup-php@v2"
+        uses: "shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc" # 2.37.1
         with:
           coverage: "none"
           extensions: "intl, zip"
@@ -73,30 +71,28 @@ jobs:
           php-version: "${{ matrix.php-version }}"
           tools: cs2pr
 
-      - name: Retrieve Composer cache directory
-        id: composer-cache
-        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
-
-      - name: "Cache dependencies installed with Composer"
-        uses: "actions/cache@v5"
+      - name: "Install Composer dependencies"
+        uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # 4.0.0
         with:
-          path: "${{ steps.composer-cache.outputs.dir }}"
-          key: "php-${{ matrix.php-version }}-symfony-php-unit-version-${{ env.SYMFONY_PHPUNIT_VERSION }}-${{ hashFiles('**/composer.lock') }}"
-          restore-keys: "php-${{ matrix.php-version }}-symfony-php-unit-version-${{ env.SYMFONY_PHPUNIT_VERSION }}"
+          dependency-versions: highest
 
-      - name: "Update dependencies from composer.json"
-        if: "matrix.experimental == true"
-        run: "composer config platform --unset && composer update ${{ env.COMPOSER_FLAGS }}"
-
-      - name: "Install dependencies from composer.lock"
-        if: "matrix.experimental == false"
-        run: "composer config platform --unset && composer install ${{ env.COMPOSER_FLAGS }}"
-
-      - name: Install PHPUnit
+      - name: "Install PHPUnit"
         run: "./vendor/bin/simple-phpunit install"
 
       - name: "Lint PHP files"
-        run: "find src/ -type f -name '*.php' -print0 | xargs -0 -L1 -P4 -- php -l -f"
+        run: |
+          hasErrors=0
+          for f in $(find src/ tests/ -type f -name '*.php' ! -path '*/vendor/*')
+          do
+            { error="$(php -derror_reporting=-1 -ddisplay_errors=1 -l -f $f 2>&1 1>&3 3>&-)"; } 3>&1;
+            if [ "$error" != "" ]; then
+              while IFS= read -r line; do echo "::error file=$f::$line"; done <<< "$error"
+              hasErrors=1
+            fi
+          done
+          if [ $hasErrors -eq 1 ]; then
+            exit 1
+          fi
 
       - name: "Run PHPStan"
         run: "./vendor/bin/phpstan analyse --error-format=checkstyle | cs2pr"
